package com.vectornode.cortexdb.models;

/**
 * Role of the converser in a conversation.
 * Mirrors the backend {@code com.vectornode.memory.entity.enums.ConverserRole}.
 */
public enum ConverserRole {
    /** Content from a human user. */
    USER,
    /** Content generated by the AI assistant. */
    AGENT,
    /** System instructions or contextual information. */
    SYSTEM,
    /** Content from a reference document. */
    DOCUMENT
}
