package com.vectornode.memory.query.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vectornode.memory.config.LLMProvider;
import com.vectornode.memory.entity.Context;
import com.vectornode.memory.entity.KnowledgeBase;
import com.vectornode.memory.entity.enums.ConverserRole;
import com.vectornode.memory.query.dto.request.QueryRequest;
import com.vectornode.memory.query.dto.response.QueryResponse;
import com.vectornode.memory.query.repository.ContextRepository;
import com.vectornode.memory.query.repository.KnowledgeBaseRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StopWatch;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mockStatic;

/**
 * Retrieval Benchmark Test — Two-Tier Architecture
 *
 * ┌─────────────────────────────────────────────────────────────────┐
 * │ TIER 1 (CI/CD): USE_REAL_LLM=false (default) │
 * │ Embedder: Deterministic Bag-of-Words (free, instant) │
 * │ Dataset: dummy_benchmark.json (25 items, 8 queries) │
 * │ Purpose: Regression test on every push │
 * ├─────────────────────────────────────────────────────────────────┤
 * │ TIER 2 (Paper): USE_REAL_LLM=true │
 * │ Embedder: gemini-embedding-001 via Gemini API (real) │
 * │ Dataset: hotpot_benchmark.json (generated by adapter) │
 * │ Purpose: Official benchmark evaluation metrics │
 * │ Requires: GEMINI_API_KEY env var set │
 * └─────────────────────────────────────────────────────────────────┘
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE, properties = {
        "spring.main.allow-bean-definition-overriding=true",
        "management.endpoints.enabled-by-default=false",
        "spring.ai.azure.openai.endpoint=https://dummy.openai.azure.com",
        "spring.ai.azure.openai.api-key=dummy-key",
        "spring.ai.openai.api-key=dummy-key"
})
@Transactional
class RetrievalBenchmarkTest {

    private static final Logger log = LoggerFactory.getLogger(RetrievalBenchmarkTest.class);

    @Autowired
    private QueryService queryService;

    @Autowired
    private KnowledgeBaseRepository knowledgeBaseRepository;

    @Autowired
    private ContextRepository contextRepository;

    @Autowired
    private ObjectMapper objectMapper;

    private JsonNode benchmarkData;
    private MockedStatic<LLMProvider> mockedLLM;
    private boolean useRealLlm;

    @BeforeEach

    void setUp() throws Exception {
        // ── Tier Selection ──
        // Checks both Maven system property (-DuseRealLlm=true) and env var (USE_REAL_LLM=true)
        String realLlmFlag = System.getProperty("useRealLlm", System.getenv("USE_REAL_LLM"));
        useRealLlm = Boolean.parseBoolean(realLlmFlag);

        // 1. Select dataset based on tier
        String datasetFile;
        if (useRealLlm) {
            datasetFile = "/hotpot_benchmark.json";
            log.info("▶ TIER 2 MODE: Using real LLM embeddings with HotpotQA dataset");
        } else {
            datasetFile = "/dummy_benchmark.json";
            log.info("▶ TIER 1 MODE: Using mock embeddings with dummy dataset");
        }

        try (InputStream is = getClass().getResourceAsStream(datasetFile)) {
            if (is == null) {
                throw new IllegalStateException(
                        "Dataset not found: " + datasetFile +
                                (useRealLlm ? "\nRun 'python scripts/hotpot_adapter.py' first to generate it." : ""));
            }
            benchmarkData = objectMapper.readTree(is);
        }

        // 2. Configure Embedder
        if (useRealLlm) {
            // ── TIER 2: Load config from .env file (same pattern as EmbeddingIntegrationTest) ──
            Map<String, String> envVars = loadEnvFile();
            String provider = resolveVar(envVars, "LLM_PROVIDER", "GEMINI");
            String apiKey = resolveVar(envVars, "LLM_API_KEY", null);
            String chatModel = resolveVar(envVars, "LLM_CHAT_MODEL", "gemini-2.0-flash");
            String embedModel = resolveVar(envVars, "LLM_EMBED_MODEL", "gemini-embedding-001");

            if (apiKey == null || apiKey.isBlank()) {
                throw new IllegalStateException(
                        "LLM_API_KEY not found in .env file or environment. " +
                        "Please set it in memory/.env for Tier 2 benchmark mode.");
            }

            new LLMProvider(provider, apiKey, null, chatModel, embedModel);
            log.info("  Real LLMProvider initialized (provider={}, embedModel={})", provider, embedModel);
            // No mocking — LLMProvider.getEmbedding() will make real API calls
        } else {
            // ── TIER 1: Mock with deterministic bag-of-words ──
            mockedLLM = mockStatic(LLMProvider.class);
            mockedLLM.when(() -> LLMProvider.getEmbedding(anyString())).thenAnswer(invocation -> {
                String text = invocation.getArgument(0, String.class);
                return generateDeterministicVector(text);
            });
        }

        // 3. Clear DB
        contextRepository.deleteAll();
        knowledgeBaseRepository.deleteAll();

        // 4. Ingest History from JSON
        JsonNode history = benchmarkData.get("ingestion_history");
        int totalItems = history.size();
        log.info("  Ingesting {} chunks into database...", totalItems);

        for (int i = 0; i < totalItems; i++) {
            JsonNode item = history.get(i);
            String content = item.get("content").asText();

            float[] embedding = useRealLlm
                    ? LLMProvider.getEmbedding(content)
                    : generateDeterministicVector(content);

            KnowledgeBase kb = new KnowledgeBase();
            kb.setUid("benchmark-user");
            kb.setConverser(ConverserRole.valueOf(item.get("role").asText()));
            kb.setContent(content);
            kb.setVectorEmbedding(embedding);
            knowledgeBaseRepository.save(kb);

            Context ctx = new Context();
            ctx.setKnowledgeBase(kb);
            ctx.setTextChunk(content);
            ctx.setVectorEmbedding(embedding);
            ctx.setChunkIndex(0);
            contextRepository.save(ctx);

            // Progress logging for large datasets
            if (totalItems > 50 && (i + 1) % 50 == 0) {
                log.info("  Ingested {}/{} chunks...", i + 1, totalItems);
            }
        }
        log.info("  Ingestion complete: {} chunks loaded.", totalItems);
    }

    @AfterEach
    void tearDown() {
        if (mockedLLM != null) {
            mockedLLM.close();
        }
    }

    @Test
    @DisplayName("Evaluate Recall@K, MRR, Context Precision, and Latency")
    void runBenchmarkEvaluations() {
        JsonNode queries = benchmarkData.get("benchmark_queries");
        int K = 5;
        int numQueries = queries.size();

        double totalRecall = 0;
        double totalMRR = 0;
        double totalPrecision = 0;
        long totalLatencyMs = 0;

        String tierLabel = useRealLlm ? "TIER 2 — Real LLM (gemini-embedding-001)" : "TIER 1 — Mock (Bag-of-Words)";

        System.out.println();
        System.out.println("=".repeat(100));
        System.out.printf("  %s%n", tierLabel);
        System.out.printf("  Dataset: %d chunks  |  Queries: %d  |  K=%d%n",
                benchmarkData.get("ingestion_history").size(), numQueries, K);
        System.out.println("=".repeat(100));

        for (int q = 0; q < numQueries; q++) {
            JsonNode queryNode = queries.get(q);
            String queryId = queryNode.get("query_id").asText();
            String prompt = queryNode.get("user_prompt").asText();

            List<String> expectedSnippets = new ArrayList<>();
            queryNode.get("expected_ground_truth_snippets").forEach(n -> expectedSnippets.add(n.asText()));

            QueryRequest request = QueryRequest.builder()
                    .query(prompt)
                    .limit(K)
                    .build();

            // Measure Latency
            StopWatch stopWatch = new StopWatch();
            stopWatch.start();
            QueryResponse response = queryService.searchContexts(request);
            stopWatch.stop();
            long queryLatency = stopWatch.getTotalTimeMillis();
            totalLatencyMs += queryLatency;

            List<QueryResponse.SearchResult> results = response.getResults();

            // --- Recall@K ---
            int snippetsFound = 0;
            for (String expected : expectedSnippets) {
                boolean found = false;
                for (QueryResponse.SearchResult result : results) {
                    if (contentMatches(expected, result.getContent())) {
                        found = true;
                        break;
                    }
                }
                if (found)
                    snippetsFound++;
            }
            double queryRecall = (double) snippetsFound / expectedSnippets.size();
            totalRecall += queryRecall;

            // --- MRR ---
            double queryMRR = 0.0;
            for (int i = 0; i < results.size(); i++) {
                String returnedContent = results.get(i).getContent();
                boolean isRelevant = false;
                for (String expected : expectedSnippets) {
                    if (contentMatches(expected, returnedContent)) {
                        isRelevant = true;
                        break;
                    }
                }
                if (isRelevant) {
                    queryMRR = 1.0 / (i + 1);
                    break;
                }
            }
            totalMRR += queryMRR;

            // --- Context Precision ---
            int relevantCount = 0;
            for (QueryResponse.SearchResult result : results) {
                for (String expected : expectedSnippets) {
                    if (contentMatches(expected, result.getContent())) {
                        relevantCount++;
                        break;
                    }
                }
            }
            double queryPrecision = results.isEmpty() ? 0.0 : (double) relevantCount / results.size();
            totalPrecision += queryPrecision;

            // Per-query report
            System.out.printf("  [%s] \"%s\"%n", queryId, truncate(prompt, 80));
            System.out.printf(
                    "         Recall: %.2f (%d/%d) | MRR: %.2f | Precision: %.2f | Latency: %dms%n",
                    queryRecall, snippetsFound, expectedSnippets.size(), queryMRR, queryPrecision, queryLatency);
            System.out.printf("         Top-%d: %s%n", K,
                    results.stream().map(r -> truncate(r.getContent(), 45)).toList());
            System.out.println("-".repeat(100));
        }

        double avgRecall = totalRecall / numQueries;
        double avgMRR = totalMRR / numQueries;
        double avgPrecision = totalPrecision / numQueries;
        double avgLatency = (double) totalLatencyMs / numQueries;

        System.out.println();
        System.out.println("=".repeat(100));
        System.out.printf("  AGGREGATE RESULTS  (%s)%n", tierLabel);
        System.out.printf("    Recall@%d:          %.4f%n", K, avgRecall);
        System.out.printf("    MRR:               %.4f%n", avgMRR);
        System.out.printf("    Context Precision: %.4f%n", avgPrecision);
        System.out.printf("    Avg Latency:       %.2f ms%n", avgLatency);
        System.out.println("=".repeat(100));
        System.out.println();

        // Thresholds differ by tier
        if (useRealLlm) {
            // Tier 2: Higher expectations with real embeddings
            assertThat(avgRecall)
                    .as("Tier 2 Recall@%d should exceed 0.5 with real embeddings", K)
                    .isGreaterThanOrEqualTo(0.5);
            assertThat(avgMRR)
                    .as("Tier 2 MRR should exceed 0.4 with real embeddings")
                    .isGreaterThanOrEqualTo(0.4);
        } else {
            // Tier 1: Lenient thresholds for bag-of-words mock
            assertThat(avgRecall)
                    .as("Tier 1 Recall@%d should meet minimum regression threshold", K)
                    .isGreaterThanOrEqualTo(0.3);
            assertThat(avgMRR)
                    .as("Tier 1 MRR should meet minimum regression threshold")
                    .isGreaterThanOrEqualTo(0.2);
        }
    }

    /**
     * Check if the expected snippet appears in the actual content.
     * Uses normalized substring matching.
     */
    private boolean contentMatches(String expectedSnippet, String actualContent) {
        if (actualContent == null || expectedSnippet == null)
            return false;
        String normExpected = expectedSnippet.toLowerCase().replaceAll("[^a-z0-9 ]", "").trim();
        String normActual = actualContent.toLowerCase().replaceAll("[^a-z0-9 ]", "").trim();
        return normActual.contains(normExpected) || normExpected.contains(normActual);
    }

    private String truncate(String s, int maxLen) {
        if (s == null)
            return "null";
        return s.length() <= maxLen ? s : s.substring(0, maxLen) + "...";
    }

    /**
     * Pure deterministic Bag-of-Words embedding generator (Tier 1 only).
     *
     * Each word is hashed to positions in a 1024-dim vector. L2-normalized.
     * NO synonym boosts. This is intentionally a weak baseline.
     */
    private float[] generateDeterministicVector(String text) {
        float[] vector = new float[1024];
        String[] words = text.toLowerCase().replaceAll("[^a-z0-9 ]", "").split("\\s+");

        for (String word : words) {
            if (!word.isBlank()) {
                int h1 = Math.abs(word.hashCode()) % 1024;
                int h2 = Math.abs((word.hashCode() * 31 + 7) % 1024);
                vector[h1] += 1.0f;
                vector[h2] += 0.5f;
            }
        }

        // L2 normalize
        float sumSq = 0;
        for (float v : vector)
            sumSq += v * v;
        if (sumSq > 0) {
            float mag = (float) Math.sqrt(sumSq);
            for (int i = 0; i < 1024; i++)
                vector[i] /= mag;
        }
        return vector;
    }

    // ── .env file loading (same pattern as EmbeddingIntegrationTest) ──

    private static String resolveVar(Map<String, String> envVars, String name, String defaultValue) {
        String value = envVars.get(name);
        if (value != null && !value.isEmpty()) return value;
        value = System.getenv(name);
        if (value != null && !value.isEmpty()) return value;
        return defaultValue;
    }

    private static Map<String, String> loadEnvFile() {
        Map<String, String> envVars = new HashMap<>();
        Path envPath = Paths.get("").toAbsolutePath();

        while (envPath != null) {
            Path envFile = envPath.resolve(".env");
            if (Files.exists(envFile)) {
                try {
                    Files.lines(envFile).forEach(line -> {
                        line = line.trim();
                        if (!line.isEmpty() && !line.startsWith("#") && line.contains("=")) {
                            int eqIndex = line.indexOf("=");
                            String key = line.substring(0, eqIndex).trim();
                            String value = line.substring(eqIndex + 1).trim();
                            envVars.put(key, value);
                        }
                    });
                    break;
                } catch (IOException e) {
                    // Ignore
                }
            }
            envPath = envPath.getParent();
        }
        return envVars;
    }
}
