/**
 * TypeScript data models mirroring the Java DTOs.
 *
 * Because JavaScript handles JSON objects natively and the Java backend
 * expects camelCase, we don't need any field aliasing — plain interfaces
 * map directly to the API payloads.
 */

// ─── Enums ───────────────────────────────────────────────────────────

export enum LLMApiProvider {
    GEMINI = "GEMINI",
    OPENAI = "OPENAI",
    ANTHROPIC = "ANTHROPIC",
    AZURE = "AZURE",
    OPENROUTER = "OPENROUTER",
}

export enum ConverserRole {
    /** Represents content from a human user. */
    USER = "USER",
    /** Represents content generated by the AI assistant. */
    AGENT = "AGENT",
    SYSTEM = "SYSTEM",
}

// ─── Setup ───────────────────────────────────────────────────────────

export interface SetupRequest {
    provider: LLMApiProvider;
    apiKey?: string;
    chatModelName: string;
    embedModelName: string;
    baseUrl?: string;
}

export interface SetupResponse {
    message: string;
    success: boolean;
    configuredProvider?: string;
    configuredChatModel?: string;
    configuredEmbedModel?: string;
    baseUrl?: string;
    timestamp?: string;
}

// ─── Ingest ──────────────────────────────────────────────────────────

export interface IngestRequest {
    uid: string;
    converser: ConverserRole;
    content: string;
    metadata?: Record<string, any>;
}

export interface KnowledgeBase {
    /** Simplified KnowledgeBase entity returned in ingest responses. */
    id?: string;
    uid?: string;
    content?: string;
    createdAt?: string;
}

export interface IngestResponse {
    knowledgeBase?: KnowledgeBase;
    status?: string;
    message?: string;
    processingTimeMs?: number;
    embeddingTimeMs?: number;
}

// ─── Query ───────────────────────────────────────────────────────────

export interface QueryRequest {
    query: string;
    limit: number;
    minRelevance: number;
    filters?: Record<string, any>;
}

export interface SearchResult {
    id?: string;
    content?: string;
    score?: number;
    type?: string;
    metadata?: Record<string, any>;
}

export interface QueryResponse {
    query?: string;
    results: SearchResult[];
    processingTimeMs?: number;
}

// ─── Entity / Relation ───────────────────────────────────────────────

export interface Entity {
    /** RagEntity returned from entity endpoints. */
    id?: string;
    name?: string;
    type?: string;
    description?: string;
    embedding?: number[];
}

export interface Relation {
    /** Relation between two entities. */
    id?: string;
    sourceEntityId?: string;
    targetEntityId?: string;
    relationType?: string;
    weight?: number;
}
