"""Pydantic data models mirroring the Java DTOs."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


# ─── Enums ───────────────────────────────────────────────────────────


class LLMApiProvider(str, Enum):
    OPENAI = "OPENAI"
    AZURE = "AZURE"
    OLLAMA = "OLLAMA"
    ANTHROPIC = "ANTHROPIC"
    GEMINI = "GEMINI"
    MISTRAL = "MISTRAL"


class ConverserRole(str, Enum):
    USER = "USER" #represents content from a human user.
    AGENT = "AGENT"# represents content generated by the AI aasistant.
    SYSTEM = "SYSTEM"


# ─── Setup ───────────────────────────────────────────────────────────


class SetupRequest(BaseModel):
    provider: LLMApiProvider
    api_key: str | None = Field(default=None, alias="apiKey")
    chat_model_name: str = Field(alias="chatModelName")
    embed_model_name: str = Field(alias="embedModelName")
    base_url: str | None = Field(default=None, alias="baseUrl")

    model_config = {"populate_by_name": True}


class SetupResponse(BaseModel):
    message: str
    success: bool
    configured_provider: str | None = Field(default=None, alias="configuredProvider")
    configured_chat_model: str | None = Field(
        default=None, alias="configuredChatModel"
    )
    configured_embed_model: str | None = Field(
        default=None, alias="configuredEmbedModel"
    )
    base_url: str | None = Field(default=None, alias="baseUrl")
    timestamp: datetime | None = None

    model_config = {"populate_by_name": True}


# ─── Ingest ──────────────────────────────────────────────────────────


class IngestRequest(BaseModel):
    uid: str
    converser: ConverserRole
    content: str
    metadata: dict[str, Any] | None = None


class KnowledgeBase(BaseModel):
    """Simplified KnowledgeBase entity returned in ingest responses."""

    id: UUID | None = None
    uid: str | None = None
    content: str | None = None
    created_at: datetime | None = Field(default=None, alias="createdAt")

    model_config = {"populate_by_name": True}


class IngestResponse(BaseModel):
    knowledge_base: KnowledgeBase | None = Field(
        default=None, alias="knowledgeBase"
    )
    status: str | None = None
    message: str | None = None
    processing_time_ms: int | None = Field(default=None, alias="processingTimeMs")
    embedding_time_ms: int | None = Field(default=None, alias="embeddingTimeMs")

    model_config = {"populate_by_name": True}


# ─── Query ───────────────────────────────────────────────────────────


class QueryRequest(BaseModel):
    query: str
    limit: int = 5
    min_relevance: float = Field(default=0.7, alias="minRelevance")
    filters: dict[str, Any] | None = None

    model_config = {"populate_by_name": True}


class SearchResult(BaseModel):
    id: UUID | None = None
    content: str | None = None
    score: float | None = None
    type: str | None = None
    metadata: dict[str, Any] | None = None


class QueryResponse(BaseModel):
    query: str | None = None
    results: list[SearchResult] = Field(default_factory=list)
    processing_time_ms: int | None = Field(default=None, alias="processingTimeMs")

    model_config = {"populate_by_name": True}


# ─── Entity / Relation ───────────────────────────────────────────────


class Entity(BaseModel):
    """RagEntity returned from entity endpoints."""

    id: UUID | None = None
    name: str | None = None
    type: str | None = None
    description: str | None = None
    embedding: list[float] | None = None

    model_config = {"populate_by_name": True}


class Relation(BaseModel):
    """Relation between two entities."""

    id: UUID | None = None
    source_entity_id: UUID | None = Field(default=None, alias="sourceEntityId")
    target_entity_id: UUID | None = Field(default=None, alias="targetEntityId")
    relation_type: str | None = Field(default=None, alias="relationType")
    weight: float | None = None

    model_config = {"populate_by_name": True}
