package com.vectornode.memory.entity.enums;

public enum ConverserRole {
    USER, // represents content from a human user.
    AGENT, // represents content generated by the AI assistant.
    SYSTEM // reresents system instructions or contextual information.
}