package com.vectornode.memory.entity.enums;

public enum ConverserRole {
    USER, // represents content from a human user.
    AGENT, // represents content generated by the AI assistant.
    SYSTEM, // represents system instructions or contextual information.
    DOCUMENT // represents an imported reference document.
}